[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'cache_forge'
optimizer = true
optimizer_runs = 10

# ir based compilation
via_ir = true

ignored_error_codes = [ "unused-param", "unused-var", "license", "code-size", "init-code-size", "unused-param", "unused-return" ]

[invariant]
# fail_on_revert = true
# show_metrics = true